# Generated by Django 4.2.17 on 2026-03-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('ENGINEERING', 'Engineering'), ('DESIGN', 'Design'), ('PRODUCT', 'Product'), ('MARKETING', 'Marketing'), ('HR', 'HR'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
    ]
